3887352: Include submission period in PoM submissions details page
DEFRA/epr-regulator-service pull request #28
Opened 2024-06-12 11:01 UTC by nadir2khanexternal

https://dev.azure.com/defragovuk/RWD-CPR-EPR4P-ADO/_workitems/edit/387352

2024-06-12 11:12 UTC, scdefra requested changes

2024-06-12 11:12 UTC, scdefra commented on src/EPR.RegulatorService.Frontend.Web/Views/Shared/Partials/_ResubmissionDetails.cshtml
> +                @Localizer["SummaryList.Title"]@if (!string.IsNullOrEmpty(Model.SubmissionPeriod))
Please fix the formatting here

2024-06-12 11:34 UTC, nadir2khanexternal commented on src/EPR.RegulatorService.Frontend.Web/Views/Shared/Partials/_ResubmissionDetails.cshtml
> +                @Localizer["SummaryList.Title"]@if (!string.IsNullOrEmpty(Model.SubmissionPeriod))
resolved don

2024-06-12 11:35 UTC, JawwadBaigEviden approved these changes

2024-06-12 11:42 UTC, scdefra approved these changes

2024-06-13 09:29 UTC, scdefra approved these changes

2024-06-13 09:37 UTC, merged